#!/bin/bash
# Deriva arquivos de config (firmware C header, mosquitto ACL/passwd,
# companion-compose .env) a partir do .env raiz.
# Schema dinâmico: itera sobre HOSTS=csv pra gerar quantos coletores forem.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

if [[ ! -f .env ]]; then
  echo "✗ .env não existe. Copie .env.example e ajuste antes." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a; source .env; set +a

# ─── Validações cedo ─────────────────────────────────────────────────────────
if [[ -z "${HOSTS:-}" ]]; then
  echo "✗ HOSTS vazio em .env. Defina HOSTS=<id1>,<id2>,..." >&2
  exit 1
fi
if [[ -z "${MQTT_BROKER_HOST:-}" ]]; then
  echo "✗ MQTT_BROKER_HOST vazio. Defina = <id> de um host em HOSTS." >&2
  exit 1
fi
if [[ -z "${COMPANION_HOST:-}" ]]; then
  echo "✗ COMPANION_HOST vazio. Defina = <id> de um host em HOSTS." >&2
  exit 1
fi

IFS=',' read -ra HOST_IDS <<< "${HOSTS}"

# Trim de cada id (remove espaços)
HOST_IDS_TRIMMED=()
for id in "${HOST_IDS[@]}"; do
  trimmed="${id// /}"
  [[ -n "${trimmed}" ]] && HOST_IDS_TRIMMED+=("${trimmed}")
done

# Resolve IP do broker (referenciado por MQTT_BROKER_HOST)
broker_ip_var="HOST_${MQTT_BROKER_HOST}_IP"
MQTT_BROKER_IP="${!broker_ip_var:-}"
if [[ -z "${MQTT_BROKER_IP}" ]]; then
  echo "✗ ${broker_ip_var} não definido em .env (MQTT_BROKER_HOST=${MQTT_BROKER_HOST})" >&2
  exit 1
fi

mkdir -p firmware/include companion-compose mosquitto-config telegraf-configs

# ─── 1) firmware/include/generated_config.h ──────────────────────────────────
{
  echo "// AUTO-GENERATED by scripts/generate-envs.sh — DO NOT EDIT MANUALLY"
  echo "#pragma once"
  echo ""
  echo "#define MQTT_DEFAULT_HOST    \"${MQTT_BROKER_IP}\""
  echo "#define MQTT_DEFAULT_PORT    ${MQTT_PORT}"
  echo "#define MQTT_USER_DISPLAY    \"${MQTT_USER_DISPLAY}\""
  echo ""
  echo "#define TOPIC_PREFIX_STATS         \"${TOPIC_PREFIX_STATS}\""
  echo "#define TOPIC_PREFIX_BACKUPS       \"${TOPIC_PREFIX_BACKUPS}\""
  echo "#define TOPIC_PREFIX_WEATHER       \"${TOPIC_PREFIX_WEATHER}\""
  echo "#define TOPIC_PREFIX_NOTIFICATIONS \"${TOPIC_PREFIX_NOTIFICATIONS}\""
  echo "#define TOPIC_CLAUDE_USAGE         \"${TOPIC_CLAUDE_USAGE}\""
  echo "#define TOPIC_DISPLAY_HEALTH       \"${TOPIC_DISPLAY_HEALTH}\""
  echo "#define TOPIC_DISPLAY_STATUS       \"${TOPIC_DISPLAY_STATUS}\""
  echo "#define TOPIC_DISPLAY_FW_STATUS    \"${TOPIC_DISPLAY_FW_STATUS}\""
  echo "#define TOPIC_CONTROL_FW_MANIFEST  \"${TOPIC_CONTROL_FW_MANIFEST}\""
  echo ""
  echo "#define NTP_DEFAULT_SERVER   \"${NTP_SERVER}\""
  echo "#define FIRMWARE_SERVER_HOST \"${MQTT_BROKER_IP}\""
  echo "#define FIRMWARE_SERVER_PORT ${FIRMWARE_SERVER_PORT}"
  echo "#define FW_VERSION           \"${FIRMWARE_VERSION_DEFAULT}\""
  echo ""
  echo "#define HOSTS_COUNT ${#HOST_IDS_TRIMMED[@]}"
  echo "static const struct { const char *hostname; const char *label; } HOSTS[] = {"
  for id in "${HOST_IDS_TRIMMED[@]}"; do
    label_var="HOST_${id}_LABEL"
    label="${!label_var:-${id}}"
    echo "  {\"${id}\", \"${label}\"},"
  done
  echo "};"
  echo ""
  # Weather
  if [[ -n "${WEATHER_CITIES:-}" ]]; then
    IFS=',' read -ra CITY_IDS <<< "${WEATHER_CITIES}"
    echo "#define WEATHER_CITIES_COUNT ${#CITY_IDS[@]}"
    echo "static const struct { const char *id; const char *label; float lat; float lon; } WEATHER_CITIES_LIST[] = {"
    for city in "${CITY_IDS[@]}"; do
      city_trim="${city// /}"
      [[ -z "${city_trim}" ]] && continue
      label_var="WEATHER_${city_trim}_LABEL"
      lat_var="WEATHER_${city_trim}_LAT"
      lon_var="WEATHER_${city_trim}_LON"
      echo "  {\"${city_trim}\", \"${!label_var:-${city_trim}}\", ${!lat_var:-0.0}f, ${!lon_var:-0.0}f},"
    done
    echo "};"
  else
    echo "#define WEATHER_CITIES_COUNT 0"
    echo "static const struct { const char *id; const char *label; float lat; float lon; } WEATHER_CITIES_LIST[] = {};"
  fi
} > firmware/include/generated_config.h
echo "✓ firmware/include/generated_config.h"

# ─── 2) companion-compose/.env (companion daemons) ────────────────────────────
companion_collector_user="collector-${COMPANION_HOST}"
companion_daemon_user="daemon-${COMPANION_HOST}"
companion_collector_pass_file="secrets/${companion_collector_user}.pass"
companion_daemon_pass_file="secrets/${companion_daemon_user}.pass"

if [[ -f "${companion_collector_pass_file}" && -f "${companion_daemon_pass_file}" ]]; then
  MQTT_PASS_COLLECTOR=$(cat "${companion_collector_pass_file}")
  MQTT_PASS_DAEMON=$(cat "${companion_daemon_pass_file}")
else
  MQTT_PASS_COLLECTOR=""
  MQTT_PASS_DAEMON=""
  echo "⚠ secrets/ incompleto — rode scripts/generate-secrets.sh primeiro" >&2
  echo "  esperado: ${companion_collector_pass_file}, ${companion_daemon_pass_file}" >&2
fi

{
  echo "UID=$(id -u)"
  echo "GID=$(id -g)"
  echo "MQTT_HOST=${MQTT_BROKER_IP}"
  echo "MQTT_PORT=${MQTT_PORT}"
  echo "MQTT_USER_DAEMON=${companion_daemon_user}"
  echo "MQTT_USER_COLLECTOR=${companion_collector_user}"
  echo "MQTT_PASS_DAEMON=${MQTT_PASS_DAEMON}"
  echo "MQTT_PASS_COLLECTOR=${MQTT_PASS_COLLECTOR}"
  echo "HOSTNAME=${COMPANION_HOST}"
  echo "BACKUP_LOG_PATH=${BACKUP_LOG_PATH:-}"
  echo "BACKUP_BATCH_SIZE=${BACKUP_BATCH_SIZE:-18}"
  echo "BACKUP_BATCH_IDLE_SECONDS=${BACKUP_BATCH_IDLE_SECONDS:-60}"
  echo "TOPIC_PREFIX_NOTIFICATIONS=${TOPIC_PREFIX_NOTIFICATIONS}"
  echo "TOPIC_PREFIX_BACKUPS=${TOPIC_PREFIX_BACKUPS}"
  echo "TOPIC_CLAUDE_USAGE=${TOPIC_CLAUDE_USAGE}"
  echo "LOG_LEVEL=${LOG_LEVEL:-INFO}"
  echo "TZ=${TZ:-UTC}"
} > companion-compose/.env
chmod 600 companion-compose/.env
echo "✓ companion-compose/.env"

# ─── 3) mosquitto-config/acl (1 bloco por host coletor) ──────────────────────
{
  echo "# AUTO-GENERATED by scripts/generate-envs.sh"
  echo ""
  echo "user ${MQTT_USER_ADMIN}"
  echo "topic readwrite #"
  echo ""
  for id in "${HOST_IDS_TRIMMED[@]}"; do
    collect_var="HOST_${id}_COLLECT"
    collect="${!collect_var:-none}"
    [[ "${collect}" == "none" ]] && continue
    echo "user collector-${id}"
    echo "topic write ${TOPIC_PREFIX_STATS}/${id}/#"
    echo ""
  done
  echo "user ${MQTT_USER_COLLECTOR_DATA}"
  echo "topic write ${TOPIC_PREFIX_WEATHER}/#"
  echo "topic write data/status"
  echo ""
  echo "user ${companion_daemon_user}"
  echo "topic write ${TOPIC_PREFIX_NOTIFICATIONS}/#"
  echo "topic write ${TOPIC_PREFIX_BACKUPS}/${COMPANION_HOST}/#"
  echo "topic write ${TOPIC_CLAUDE_USAGE}"
  echo ""
  echo "user ${MQTT_USER_DISPLAY}"
  echo "topic read ${TOPIC_PREFIX_STATS}/#"
  echo "topic read ${TOPIC_PREFIX_BACKUPS}/#"
  echo "topic read ${TOPIC_PREFIX_WEATHER}/#"
  echo "topic read ${TOPIC_PREFIX_NOTIFICATIONS}/#"
  echo "topic read ${TOPIC_CLAUDE_USAGE}"
  echo "topic read ${TOPIC_CONTROL_FW_MANIFEST}"
  echo "topic write ${TOPIC_DISPLAY_HEALTH}"
  echo "topic write ${TOPIC_DISPLAY_STATUS}"
  echo "topic write ${TOPIC_DISPLAY_FW_STATUS}"
} > mosquitto-config/acl
echo "✓ mosquitto-config/acl"

# ─── 4) mosquitto-config/passwd (plain text; mosquitto_passwd -U pra bcrypt) ─
# IMPORTANTE: SEM comentários no arquivo — mosquitto_passwd -U rejeita.
# Documentação fica neste script + README do mosquitto-config/.
{
  for user_pass_file in secrets/*.pass; do
    [ -e "$user_pass_file" ] || continue
    user=$(basename "$user_pass_file" .pass)
    pass=$(cat "$user_pass_file")
    echo "${user}:${pass}"
  done
} > mosquitto-config/passwd
chmod 600 mosquitto-config/passwd
echo "✓ mosquitto-config/passwd (plain; needs mosquitto_passwd -U)"

echo ""
echo "✓ Todos os arquivos derivados gerados a partir de .env."
