#!/bin/bash
# Gera senhas aleatórias pros users MQTT, iterando dinamicamente sobre HOSTS.
# NÃO mexe em mosquitto rodando — só produz arquivos em secrets/.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_DIR="${REPO_ROOT}/secrets"

mkdir -p "${SECRETS_DIR}"
chmod 700 "${SECRETS_DIR}"

if [[ ! -f "${REPO_ROOT}/.env" ]]; then
  echo "✗ .env não existe. Copie .env.example e ajuste antes." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a; source "${REPO_ROOT}/.env"; set +a

if [[ -z "${HOSTS:-}" ]]; then
  echo "✗ HOSTS vazio em .env. Defina HOSTS=<id1>,<id2>,..." >&2
  exit 1
fi

IFS=',' read -ra HOST_IDS <<< "${HOSTS}"

# Builda lista de users dinamicamente
USERS=("${MQTT_USER_ADMIN}" "${MQTT_USER_COLLECTOR_DATA}" "${MQTT_USER_DISPLAY}")

# 1 user coletor por host com COLLECT != none
for id in "${HOST_IDS[@]}"; do
  id_trimmed="${id// /}"   # remove espaços
  [[ -z "${id_trimmed}" ]] && continue
  collect_var="HOST_${id_trimmed}_COLLECT"
  collect="${!collect_var:-none}"
  if [[ "${collect}" == "none" ]]; then
    continue
  fi
  USERS+=("collector-${id_trimmed}")
done

# Daemon do companion (se COMPANION_HOST setado)
if [[ -n "${COMPANION_HOST:-}" ]]; then
  USERS+=("daemon-${COMPANION_HOST}")
fi

# Gerar senha pra cada user (idempotente: preserva existentes)
for user in "${USERS[@]}"; do
  pass_file="${SECRETS_DIR}/${user}.pass"
  if [[ -f "${pass_file}" ]]; then
    echo "✓ ${user}: senha já existe (preservada)"
    continue
  fi
  password=$(openssl rand -base64 24 | tr -d '\n')
  printf '%s' "${password}" > "${pass_file}"
  chmod 600 "${pass_file}"
  echo "✓ ${user}: gerada"
done

# firmware/include/secrets.h com a senha do display (consumido pelo firmware)
mkdir -p "${REPO_ROOT}/firmware/include"
{
  echo "// AUTO-GENERATED by scripts/generate-secrets.sh — DO NOT EDIT MANUALLY"
  echo "// gitignored — não commita."
  echo "#pragma once"
  echo ""
  display_pass_file="${SECRETS_DIR}/${MQTT_USER_DISPLAY}.pass"
  if [[ -f "${display_pass_file}" ]]; then
    pass=$(cat "${display_pass_file}")
    echo "#define MQTT_DISPLAY_PASS \"${pass}\""
  fi
} > "${REPO_ROOT}/firmware/include/secrets.h"
chmod 600 "${REPO_ROOT}/firmware/include/secrets.h"
echo "✓ firmware/include/secrets.h (mode 600)"

echo ""
echo "⚠ IMPORTANTE: copie cada ${SECRETS_DIR}/*.pass pra um password manager."
echo "  Esses arquivos ficam SOMENTE neste host (gitignored)."
echo ""
echo "Próximo passo: rodar scripts/generate-envs.sh"
